### ISSUE TITLE
Message Options bug

### ISSUE THREAD

**Issue by enorenio** [JuzSer/vue-bot-ui#10] opened 2021-01-18 11:57 UTC
Message Options becomes unclickable after closing and re-opening board. Reproducible in demo page.
Steps to reproduce:
1. Open board.
2. Send messages till bot replies with message with options.
3. Close the board
4. Open it again
5. Click on any message option. It will not work.

I have already found out how to fix this, so I'm going to create PR soon.

**Comment by enorenio** [comment] 2021-01-18 22:23
Also there's no need for `EventBus.$on('select-button-option', this.selectOption)` in create hook. I just noticed that it's not needed. I might be wrong, so can you please check it, @juzser ? It's 139th line of `./src/components/BotUI.vue`

**Comment by juzser** [comment] 2021-01-19 02:40
Thank you @enorenio !
I do not fully understand what you mean. Do you mean:
1. After the bot reponses the options
2. Close the board
3. Open again, and it's impossible to click on the options? 

I cannot reproduce the bug, I tried and see it still works well.
<img width="366" alt="Screen Shot 2021-01-19 at 09 36 33" src="https://user-images.githubusercontent.com/5735071/104980735-dea62c00-5a39-11eb-8c31-2c1b33d8d9e0.png">

**Comment by juzser** [comment] 2021-01-19 02:42
Thank you @enorenio 
I think I see what you mean about the `created` hook. 
With your new PR, we can remove the eventBus in `created` hook. 
Let me check around.

**Comment by juzser** [comment] 2021-01-19 02:51
Fixed on v0.2.6

**Closed as completed** 2021-01-19 08:51 UTC
